// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.fdn.cards

import com.wingedsheep.sdk.core.CounterType
import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.dsl.mode
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.ModalEffect
import com.wingedsheep.sdk.scripting.effects.Mode
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter


/**
 * Apothecary Stomper
 * {4}{G}{G}
 * Creature — Elephant
 * 4/4
 * Vigilance (Attacking doesn't cause this creature to tap.)
 * When this creature enters, choose one —
 * • Put two +1/+1 counters on target creature you control.
 * • You gain 4 life.
 */
val ApothecaryStomper = card("Apothecary Stomper") {
    manaCost = "{4}{G}{G}"
    colorIdentity = "G"
    typeLine = "Creature — Elephant"
    oracleText = "Vigilance (Attacking doesn't cause this creature to tap.)\nWhen this creature enters, choose one —\n• Put two +1/+1 counters on target creature you control.\n• You gain 4 life."
    power = 4
    toughness = 4
    keywords(Keyword.VIGILANCE)
    triggeredAbility {
        trigger = Triggers.self.enters()
        effect = ModalEffect.chooseOne(
            mode("Put two +1/+1 counters on target creature you control") {
                val creature = target(TargetFilter.Creature.youControl())
                effect = Effects.AddCounters(
                    counterType = CounterType.PLUS_ONE_PLUS_ONE,
                    count = 2,
                    target = creature
                )
            },
            Mode.noTarget(Effects.GainLife(4), "You gain 4 life")
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "99"
        artist = "Edgar Sánchez Hidalgo"
        flavorText = "A walking clinic with a trumpet to sound its arrival."
        imageUri = "https://cards.scryfall.io/normal/front/6/8/680b7b0c-0e1b-46ce-9917-9fc6e05aa148.jpg"
    }
}
