// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.fdn.cards

import com.wingedsheep.sdk.core.CounterType
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter


/**
 * Grappling Kraken
 * {4}{U}{U}
 * Creature — Kraken
 * 5/6
 * Landfall — Whenever a land you control enters, tap target creature an opponent controls and put a stun counter on it. (If a permanent with a stun counter would become untapped, remove one from it instead.)
 */
val GrapplingKraken = card("Grappling Kraken") {
    manaCost = "{4}{U}{U}"
    colorIdentity = "U"
    typeLine = "Creature — Kraken"
    oracleText = "Landfall — Whenever a land you control enters, tap target creature an opponent controls and put a stun counter on it. (If a permanent with a stun counter would become untapped, remove one from it instead.)"
    power = 5
    toughness = 6
    triggeredAbility {
        trigger = Triggers.a(GameObjectFilter.Land.youControl()).enters()
        val t = target(TargetFilter.Creature.opponentControls())
        effect = Effects.Tap(t) then
            Effects.AddCounters(counterType = CounterType.STUN, count = 1, target = t)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "39"
        artist = "Ben Wootten"
        flavorText = "\"Oh, settle down. She just wants a hug.\"\n—Kiora"
        imageUri = "https://cards.scryfall.io/normal/front/d/1/d1f5cab3-3fc0-448d-8252-cd55abf5b596.jpg"
    }
}
