// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.fdn.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter


/**
 * Joust Through
 * {W}
 * Instant
 * Joust Through deals 3 damage to target attacking or blocking creature. You gain 1 life.
 */
val JoustThrough = card("Joust Through") {
    manaCost = "{W}"
    colorIdentity = "W"
    typeLine = "Instant"
    oracleText = "Joust Through deals 3 damage to target attacking or blocking creature. You gain 1 life."
    spell {
        val t = target(TargetFilter.AttackingOrBlockingCreature)
        effect = Effects.DealDamage(3, t) then Effects.GainLife(1)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "19"
        artist = "Miro Petrov"
        flavorText = "\"Allow me to offer a counterpoint.\""
        imageUri = "https://cards.scryfall.io/normal/front/8/4/846adb38-f9bb-4fed-b8ed-36ec7885f989.jpg"
    }
}
