// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.fdn.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.core.CounterType
import com.wingedsheep.sdk.dsl.Conditions
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.dsl.mode
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.ModalEffect
import com.wingedsheep.sdk.scripting.effects.Mode
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.core.Step


/**
 * Sylvan Scavenging
 * {1}{G}{G}
 * Enchantment
 * At the beginning of your end step, choose one —
 * • Put a +1/+1 counter on target creature you control.
 * • Create a 3/3 green Raccoon creature token if you control a creature with power 4 or greater.
 */
val SylvanScavenging = card("Sylvan Scavenging") {
    manaCost = "{1}{G}{G}"
    colorIdentity = "G"
    typeLine = "Enchantment"
    oracleText = "At the beginning of your end step, choose one —\n• Put a +1/+1 counter on target creature you control.\n• Create a 3/3 green Raccoon creature token if you control a creature with power 4 or greater."
    triggeredAbility {
        trigger = Triggers.you.beginningOf(Step.END)
        effect = ModalEffect.chooseOne(
            mode("Put a +1/+1 counter on target creature you control") {
                val creature = target(TargetFilter.Creature.youControl())
                effect = Effects.AddCounters(
                    counterType = CounterType.PLUS_ONE_PLUS_ONE,
                    count = 1,
                    target = creature
                )
            },
            Mode.noTarget(
                Effects.If(
                    condition = Conditions.YouControl(GameObjectFilter.Creature.powerAtLeast(4)),
                    then = Effects.CreateToken(
                        power = 3,
                        toughness = 3,
                        colors = setOf(Color.GREEN),
                        creatureTypes = setOf("Raccoon")
                    )
                ),
                "Create a 3/3 green Raccoon creature token if you control a creature with power 4 or greater"
            )
        )
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "113"
        artist = "Josiah \"Jo\" Cameron"
        imageUri = "https://cards.scryfall.io/normal/front/c/3/c35b683c-d3b2-46a1-876a-81b34e8ba2fc.jpg"
    }
}
