// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.tor.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.Duration
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter


/**
 * Temporary Insanity
 * {3}{R}
 * Instant
 * Untap target creature with power less than the number of cards in your graveyard and gain control of it until end of turn. That creature gains haste until end of turn.
 */
val TemporaryInsanity = card("Temporary Insanity") {
    manaCost = "{3}{R}"
    colorIdentity = "R"
    typeLine = "Instant"
    oracleText = "Untap target creature with power less than the number of cards in your graveyard and gain control of it until end of turn. That creature gains haste until end of turn."
    spell {
        val t = target(TargetFilter.Creature)
        effect = Effects.Untap(t) then
            Effects.GainControl(t, Duration.EndOfTurn) then
            Effects.GrantKeyword(Keyword.HASTE, t)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "116"
        artist = "Mark Romanoski"
        imageUri = "https://cards.scryfall.io/normal/front/4/1/415d0678-539f-4c19-8a6e-b43e747a97de.jpg"
    }
}
