// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.pls.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.dsl.DynamicAmounts
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.references.Player


/**
 * Pygmy Kavu
 * {3}{G}
 * Creature — Kavu
 * 1/2
 * When this creature enters, draw a card for each black creature your opponents control.
 */
val PygmyKavu = card("Pygmy Kavu") {
    manaCost = "{3}{G}"
    colorIdentity = "G"
    typeLine = "Creature — Kavu"
    oracleText = "When this creature enters, draw a card for each black creature your opponents control."
    power = 1
    toughness = 2
    triggeredAbility {
        trigger = Triggers.self.enters()
        effect = Effects.DrawCards(
            DynamicAmounts.battlefield(Player.EachOpponent, GameObjectFilter.Creature.withColor(Color.BLACK)).count()
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "88"
        artist = "Greg Staples"
        flavorText = "\"We could learn a lot by watching the little ones,\" said Agnate. \"Define 'little,'\" replied Grizzlegom."
        imageUri = "https://cards.scryfall.io/normal/front/b/3/b31c69ec-feb5-430a-a3e9-3a6f3fb8ee1c.jpg"
    }
}
