// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lci.cards

import com.wingedsheep.sdk.core.CounterType
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter


/**
 * Ironpaw Aspirant
 * {1}{W}
 * Creature — Cat Warrior
 * 1/2
 * When this creature enters, put a +1/+1 counter on target creature.
 */
val IronpawAspirant = card("Ironpaw Aspirant") {
    manaCost = "{1}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Cat Warrior"
    oracleText = "When this creature enters, put a +1/+1 counter on target creature."
    power = 1
    toughness = 2
    triggeredAbility {
        trigger = Triggers.self.enters()
        val t = target(TargetFilter.Creature)
        effect = Effects.AddCounters(counterType = CounterType.PLUS_ONE_PLUS_ONE, count = 1, target = t)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "18"
        artist = "Dan Murayama Scott"
        flavorText = "\"Train your mind and your muscles with equal ferocity, cub. Without wisdom, even a mighty warrior is nothing but a bully.\"\n—Sovereign Okinec Ahau"
        imageUri = "https://cards.scryfall.io/normal/front/f/7/f70689a0-ac69-4052-84fc-9055e9e1c54b.jpg"
    }
}
