// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.lea.cards

import com.wingedsheep.sdk.dsl.DynamicAmounts
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.dsl.Targets


/**
 * Braingeyser
 * {X}{U}{U}
 * Sorcery
 * Target player draws X cards.
 */
val Braingeyser = card("Braingeyser") {
    manaCost = "{X}{U}{U}"
    colorIdentity = "U"
    typeLine = "Sorcery"
    oracleText = "Target player draws X cards."
    spell {
        val t = target(Targets.Player)
        effect = Effects.DrawCards(DynamicAmounts.xValue(), t)
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "50"
        artist = "Mark Tedin"
        imageUri = "https://cards.scryfall.io/normal/front/6/2/62b19a12-6914-430e-81ce-dcfca47884df.jpg"
    }
}
