// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ulg.cards

import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Rack and Ruin
 * {2}{R}
 * Instant
 * Destroy two target artifacts.
 */
val RackAndRuin = card("Rack and Ruin") {
    manaCost = "{2}{R}"
    colorIdentity = "R"
    typeLine = "Instant"
    oracleText = "Destroy two target artifacts."
    spell {
        targets(TargetFilter.Artifact, count = 2)
        effect = Effects.ForEachTarget(
            Effects.Move(EffectTarget.ContextTarget(0), Zone.GRAVEYARD, byDestruction = true)
        )
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "89"
        artist = "Donato Giancola"
        flavorText = "\"My people are bound by masters centuries dead. Each artifact we destroy is another link broken in that chain.\"\n—Barb Tail, viashino heretic"
        imageUri = "https://cards.scryfall.io/normal/front/a/4/a46e8f6a-3a1a-4c30-9348-4b31882267eb.jpg"
    }
}
