// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.otj.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.KeywordAbility


/**
 * Outcaster Trailblazer
 * {2}{G}
 * Creature — Human Druid
 * 4/2
 * When this creature enters, add one mana of any color.
 * Whenever another creature you control with power 4 or greater enters, draw a card.
 * Plot {2}{G} (You may pay {2}{G} and exile this card from your hand. Cast it as a sorcery on a later turn without paying its mana cost. Plot only as a sorcery.)
 */
val OutcasterTrailblazer = card("Outcaster Trailblazer") {
    manaCost = "{2}{G}"
    colorIdentity = "G"
    typeLine = "Creature — Human Druid"
    oracleText = "When this creature enters, add one mana of any color.\nWhenever another creature you control with power 4 or greater enters, draw a card.\nPlot {2}{G} (You may pay {2}{G} and exile this card from your hand. Cast it as a sorcery on a later turn without paying its mana cost. Plot only as a sorcery.)"
    power = 4
    toughness = 2
    triggeredAbility {
        trigger = Triggers.self.enters()
        effect = Effects.AddManaOfChoice()
    }
    triggeredAbility {
        trigger = Triggers.another(GameObjectFilter.Creature.powerAtLeast(4).youControl()).enters()
        effect = Effects.DrawCards(1)
    }
    keywordAbility(KeywordAbility.plot("{2}{G}"))
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "173"
        artist = "Denys Tsiperko"
        imageUri = "https://cards.scryfall.io/normal/front/3/3/33b9cd6c-d75c-4905-aa38-ff03a9c4b398.jpg"
    }
}
