// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.drk.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter
import com.wingedsheep.sdk.scripting.references.Player
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Inferno
 * {5}{R}{R}
 * Instant
 * Inferno deals 6 damage to each creature and each player.
 */
val Inferno = card("Inferno") {
    manaCost = "{5}{R}{R}"
    colorIdentity = "R"
    typeLine = "Instant"
    oracleText = "Inferno deals 6 damage to each creature and each player."
    spell {
        effect = Effects.ForEachInGroup(GroupFilter(GameObjectFilter.Creature), Effects.DealDamage(6, EffectTarget.IterationEntity)) then
            Effects.ForEachPlayer(Player.Each, Effects.DealDamage(6, EffectTarget.Controller))
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "71"
        artist = "Randy Asplund-Faith"
        flavorText = "\"Any scrap of compassion that still existed in my soul was permanently snuffed out when they cast me out into the flames.\" —Mairsil, called the Pretender"
        imageUri = "https://cards.scryfall.io/normal/front/a/6/a6b61512-5b24-424c-966f-36b595781e14.jpg"
    }
}
