// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.uds.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Carnival of Souls
 * {1}{B}
 * Enchantment
 * Whenever a creature enters, you lose 1 life and add {B}.
 */
val CarnivalOfSouls = card("Carnival of Souls") {
    manaCost = "{1}{B}"
    colorIdentity = "B"
    typeLine = "Enchantment"
    oracleText = "Whenever a creature enters, you lose 1 life and add {B}."
    triggeredAbility {
        trigger = Triggers.a(GameObjectFilter.Creature).enters()
        effect = Effects.LoseLife(1, EffectTarget.Controller) then Effects.AddMana(Color.BLACK)
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "55"
        artist = "Brian Snõddy"
        flavorText = "\"'Davvol, blast those elves.' 'Davvol, transport those troops.' No one cares that today is my birthday.\""
        imageUri = "https://cards.scryfall.io/normal/front/8/4/847340fb-9251-4439-b33b-f86bff507dcd.jpg"
    }
}
