// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.uds.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.SacrificeSelfEffect
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.EffectTarget
import com.wingedsheep.sdk.core.Step


/**
 * Masticore
 * {4}
 * Artifact Creature — Masticore
 * 4/4
 * At the beginning of your upkeep, sacrifice this creature unless you discard a card.
 * {2}: This creature deals 1 damage to target creature.
 * {2}: Regenerate this creature.
 */
val Masticore = card("Masticore") {
    manaCost = "{4}"
    colorIdentity = ""
    typeLine = "Artifact Creature — Masticore"
    oracleText = "At the beginning of your upkeep, sacrifice this creature unless you discard a card.\n{2}: This creature deals 1 damage to target creature.\n{2}: Regenerate this creature."
    power = 4
    toughness = 4
    triggeredAbility {
        trigger = Triggers.you.beginningOf(Step.UPKEEP)
        effect = Effects.PayOrSuffer(cost = Costs.pay.Discard(), suffer = SacrificeSelfEffect)
    }
    activatedAbility {
        cost = Costs.Mana("{2}")
        val t = target(TargetFilter.Creature)
        effect = Effects.DealDamage(1, t)
    }
    activatedAbility {
        cost = Costs.Mana("{2}")
        effect = Effects.Regenerate(EffectTarget.Self)
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "134"
        artist = "Paolo Parente"
        imageUri = "https://cards.scryfall.io/normal/front/9/0/908a2215-7231-43a4-8fec-5d1e4233c028.jpg"
    }
}
