// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.rna.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.DynamicAmounts
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.dsl.times
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.references.Player


/**
 * Archway Angel
 * {5}{W}
 * Creature — Angel
 * 3/4
 * Flying
 * When this creature enters, you gain 2 life for each Gate you control.
 */
val ArchwayAngel = card("Archway Angel") {
    manaCost = "{5}{W}"
    colorIdentity = "W"
    typeLine = "Creature — Angel"
    oracleText = "Flying\nWhen this creature enters, you gain 2 life for each Gate you control."
    power = 3
    toughness = 4
    keywords(Keyword.FLYING)
    triggeredAbility {
        trigger = Triggers.self.enters()
        effect = Effects.GainLife(
            DynamicAmounts.battlefield(Player.You, GameObjectFilter.Land.withSubtype("Gate")).count() * 2
        )
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "3"
        artist = "Milivoj Ćeran"
        flavorText = "A ray of hope breaks through the shroud of rain."
        imageUri = "https://cards.scryfall.io/normal/front/b/2/b209d219-b946-4226-a8b4-65a5f3837fac.jpg"
    }
}
