// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.rna.cards

import com.wingedsheep.sdk.core.AbilityFlag
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.targets.EffectTarget
import com.wingedsheep.sdk.scripting.events.Recipient


/**
 * Gateway Sneak
 * {2}{U}
 * Creature — Vedalken Rogue
 * 1/3
 * Whenever a Gate you control enters, this creature can't be blocked this turn.
 * Whenever this creature deals combat damage to a player, draw a card.
 */
val GatewaySneak = card("Gateway Sneak") {
    manaCost = "{2}{U}"
    colorIdentity = "U"
    typeLine = "Creature — Vedalken Rogue"
    oracleText = "Whenever a Gate you control enters, this creature can't be blocked this turn.\nWhenever this creature deals combat damage to a player, draw a card."
    power = 1
    toughness = 3
    triggeredAbility {
        trigger = Triggers.a(GameObjectFilter.Land.withSubtype("Gate").youControl()).enters()
        effect = Effects.GrantKeyword(AbilityFlag.CANT_BE_BLOCKED, EffectTarget.Self)
    }
    triggeredAbility {
        trigger = Triggers.self.dealsCombatDamage(Recipient.AnyPlayer)
        effect = Effects.DrawCards(1)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "40"
        artist = "Matt Stewart"
        flavorText = "\"I've been through every guildgate in this city, and no one sees me come or go.\""
        imageUri = "https://cards.scryfall.io/normal/front/e/d/edc0229d-05e6-41b7-b7a9-2a8b2b258add.jpg"
    }
}
