// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.`5dn`.cards

import com.wingedsheep.sdk.dsl.DynamicAmounts
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.references.Player
import com.wingedsheep.sdk.dsl.Targets


/**
 * Feedback Bolt
 * {4}{R}
 * Instant
 * Feedback Bolt deals damage to target player or planeswalker equal to the number of artifacts you control.
 */
val FeedbackBolt = card("Feedback Bolt") {
    manaCost = "{4}{R}"
    colorIdentity = "R"
    typeLine = "Instant"
    oracleText = "Feedback Bolt deals damage to target player or planeswalker equal to the number of artifacts you control."
    spell {
        val t = target(Targets.PlayerOrPlaneswalker)
        effect = Effects.DealDamage(DynamicAmounts.battlefield(Player.You, GameObjectFilter.Artifact).count(), t)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "64"
        artist = "Ron Spencer"
        flavorText = "The path of least resistance is often through your enemies."
        imageUri = "https://cards.scryfall.io/normal/front/a/3/a370375c-14bf-4381-9359-f2e600867e7c.jpg"
    }
}
