// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.`5dn`.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Hoverguard Sweepers
 * {6}{U}{U}
 * Creature — Drone
 * 5/6
 * Flying
 * When this creature enters, you may return up to two target creatures to their owners' hands.
 */
val HoverguardSweepers = card("Hoverguard Sweepers") {
    manaCost = "{6}{U}{U}"
    colorIdentity = "U"
    typeLine = "Creature — Drone"
    oracleText = "Flying\nWhen this creature enters, you may return up to two target creatures to their owners' hands."
    power = 5
    toughness = 6
    keywords(Keyword.FLYING)
    triggeredAbility {
        trigger = Triggers.self.enters()
        optional = true
        targets(TargetFilter.Creature, count = 2, optional = true)
        effect = Effects.ForEachTarget(Effects.Move(EffectTarget.ContextTarget(0), Zone.HAND))
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "32"
        artist = "Mark A. Nelson"
        flavorText = "They only appear in emergencies, and emergencies never last long."
        imageUri = "https://cards.scryfall.io/normal/front/5/5/55773fd5-86a2-4fd4-9849-a2f0d4c8298f.jpg"
    }
}
