// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.`5dn`.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.dsl.Targets


/**
 * Magma Jet
 * {1}{R}
 * Instant
 * Magma Jet deals 2 damage to any target. Scry 2.
 */
val MagmaJet = card("Magma Jet") {
    manaCost = "{1}{R}"
    colorIdentity = "R"
    typeLine = "Instant"
    oracleText = "Magma Jet deals 2 damage to any target. Scry 2."
    spell {
        val t = target(Targets.Any)
        effect = Effects.DealDamage(2, t) then Patterns.Library.scry(2)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "73"
        artist = "Justin Sweet"
        imageUri = "https://cards.scryfall.io/normal/front/5/1/51ea1728-08aa-4553-90b2-919c70712ed5.jpg"
    }
}
