// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.sos.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter


/**
 * Chase Inspiration
 * {U}
 * Instant
 * Target creature you control gets +0/+3 and gains hexproof until end of turn. (It can't be the target of spells or abilities your opponents control.)
 */
val ChaseInspiration = card("Chase Inspiration") {
    manaCost = "{U}"
    colorIdentity = "U"
    typeLine = "Instant"
    oracleText = "Target creature you control gets +0/+3 and gains hexproof until end of turn. (It can't be the target of spells or abilities your opponents control.)"
    spell {
        val t = target(TargetFilter.Creature.youControl())
        effect = Effects.ModifyStats(0, 3, t) then Effects.GrantKeyword(Keyword.HEXPROOF, t)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "41"
        artist = "Evyn Fong"
        flavorText = "Nothing gets in the way of a Prismari student following a great idea."
        imageUri = "https://cards.scryfall.io/normal/front/0/6/06f9f257-c7ef-44b7-8b2b-f038fba900af.jpg"
    }
}
