// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.sos.cards

import com.wingedsheep.sdk.core.CounterType
import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Conditions
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter


/**
 * Efflorescence
 * {2}{G}
 * Instant
 * Put two +1/+1 counters on target creature.
 * Infusion — If you gained life this turn, that creature also gains trample and indestructible until end of turn.
 */
val Efflorescence = card("Efflorescence") {
    manaCost = "{2}{G}"
    colorIdentity = "G"
    typeLine = "Instant"
    oracleText = "Put two +1/+1 counters on target creature.\nInfusion — If you gained life this turn, that creature also gains trample and indestructible until end of turn."
    spell {
        val t = target(TargetFilter.Creature)
        effect = Effects.AddCounters(counterType = CounterType.PLUS_ONE_PLUS_ONE, count = 2, target = t) then
            Effects.If(
                condition = Conditions.YouGainedLifeThisTurn,
                then = Effects.GrantKeyword(Keyword.TRAMPLE, t) then
                    Effects.GrantKeyword(Keyword.INDESTRUCTIBLE, t)
            )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "144"
        artist = "Tuan Duong Chu"
        flavorText = "\"Wherever your foot falls, life blossoms in its wake.\"\n—Lisette, dean of the root"
        imageUri = "https://cards.scryfall.io/normal/front/7/9/79b9ace7-eceb-4f97-9ee7-d5ee3e0b3515.jpg"
    }
}
