// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.sos.cards

import com.wingedsheep.sdk.core.CounterType
import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.EffectTarget
import com.wingedsheep.sdk.scripting.GameObjectFilter


/**
 * Hardened Academic
 * {R}{W}
 * Creature — Bird Cleric
 * 2/1
 * Flying, haste
 * Discard a card: This creature gains lifelink until end of turn.
 * Whenever one or more cards leave your graveyard, put a +1/+1 counter on target creature you control.
 */
val HardenedAcademic = card("Hardened Academic") {
    manaCost = "{R}{W}"
    colorIdentity = "WR"
    typeLine = "Creature — Bird Cleric"
    oracleText = "Flying, haste\nDiscard a card: This creature gains lifelink until end of turn.\nWhenever one or more cards leave your graveyard, put a +1/+1 counter on target creature you control."
    power = 2
    toughness = 1
    keywords(Keyword.FLYING, Keyword.HASTE)
    activatedAbility {
        cost = Costs.DiscardCard
        effect = Effects.GrantKeyword(Keyword.LIFELINK, EffectTarget.Self)
    }
    triggeredAbility {
        trigger = Triggers.oneOrMore(GameObjectFilter.Any).leaveYourGraveyard()
        val t = target(TargetFilter.Creature.youControl())
        effect = Effects.AddCounters(counterType = CounterType.PLUS_ONE_PLUS_ONE, count = 1, target = t)
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "194"
        artist = "Vincent Christiaens"
        flavorText = "\"Do you think I've spent a lifetime studying war and learned nothing?\""
        imageUri = "https://cards.scryfall.io/normal/front/0/6/06c9e8a7-2840-4cff-90af-c6636e598f78.jpg"
    }
}
