// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.sos.cards

import com.wingedsheep.sdk.core.CounterType
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.targets.EffectTarget
import com.wingedsheep.sdk.scripting.GameObjectFilter


/**
 * Spirit Mascot
 * {R}{W}
 * Creature — Spirit Ox
 * 2/2
 * Whenever one or more cards leave your graveyard, put a +1/+1 counter on this creature.
 */
val SpiritMascot = card("Spirit Mascot") {
    manaCost = "{R}{W}"
    colorIdentity = "WR"
    typeLine = "Creature — Spirit Ox"
    oracleText = "Whenever one or more cards leave your graveyard, put a +1/+1 counter on this creature."
    power = 2
    toughness = 2
    triggeredAbility {
        trigger = Triggers.oneOrMore(GameObjectFilter.Any).leaveYourGraveyard()
        effect = Effects.AddCounters(counterType = CounterType.PLUS_ONE_PLUS_ONE, count = 1, target = EffectTarget.Self)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "230"
        artist = "Edgar Sánchez Hidalgo"
        flavorText = "Unflagging, unafraid, and undaunted."
        imageUri = "https://cards.scryfall.io/normal/front/1/2/123f1fde-d8de-4640-baa1-bb3781713168.jpg"
    }
}
