// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.sos.cards

import com.wingedsheep.sdk.dsl.DynamicAmounts
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.dsl.Targets


/**
 * Traumatic Critique
 * {X}{U}{R}
 * Instant
 * Traumatic Critique deals X damage to any target. Draw two cards, then discard a card.
 */
val TraumaticCritique = card("Traumatic Critique") {
    manaCost = "{X}{U}{R}"
    colorIdentity = "UR"
    typeLine = "Instant"
    oracleText = "Traumatic Critique deals X damage to any target. Draw two cards, then discard a card."
    spell {
        val t = target(Targets.Any)
        effect = Effects.DealDamage(DynamicAmounts.xValue(), t) then
            Effects.DrawCards(2) then
            Patterns.Hand.discardCards(1)
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "239"
        artist = "Aaron Miller"
        flavorText = "\"The artist should suffer for their craft, not the audience!\"\n—Galazeth Prismari"
        imageUri = "https://cards.scryfall.io/normal/front/2/a/2a812fa7-4599-4e25-97db-20ffc6bc0b26.jpg"
    }
}
