// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.bfz.cards

import com.wingedsheep.sdk.dsl.DynamicAmounts
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.references.Player


/**
 * Stonefury
 * {3}{R}{R}
 * Instant
 * Stonefury deals damage to target creature equal to the number of lands you control.
 */
val Stonefury = card("Stonefury") {
    manaCost = "{3}{R}{R}"
    colorIdentity = "R"
    typeLine = "Instant"
    oracleText = "Stonefury deals damage to target creature equal to the number of lands you control."
    spell {
        val t = target(TargetFilter.Creature)
        effect = Effects.DealDamage(DynamicAmounts.landsYouControl(), t)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "156"
        artist = "Chris Rallis"
        flavorText = "Akoum can make any intruder look small."
        imageUri = "https://cards.scryfall.io/normal/front/6/a/6aa37f74-50dd-4013-b48a-c33f1dbfb3e1.jpg"
    }
}
