// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dft.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.CardSource
import com.wingedsheep.sdk.scripting.effects.MayPlayExpiry
import com.wingedsheep.sdk.core.Step


/**
 * Count on Luck
 * {R}{R}{R}
 * Enchantment
 * At the beginning of your upkeep, exile the top card of your library. You may play that card this turn.
 */
val CountOnLuck = card("Count on Luck") {
    manaCost = "{R}{R}{R}"
    colorIdentity = "R"
    typeLine = "Enchantment"
    oracleText = "At the beginning of your upkeep, exile the top card of your library. You may play that card this turn."
    triggeredAbility {
        trigger = Triggers.you.beginningOf(Step.UPKEEP)
        effect = Effects.Pipeline {
            val impulseExiled = gather(CardSource.TopOfLibrary(1))
            exile(impulseExiled)
            run(Effects.GrantMayPlayFromExile(impulseExiled, MayPlayExpiry.EndOfTurn))
        }
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "118"
        artist = "Michal Ivan"
        flavorText = "\"With your help, Loot, we're going to make a hell of an entrance,\" said Chandra. In less than fifteen minutes, she came to regret those words."
        imageUri = "https://cards.scryfall.io/normal/front/8/f/8f31beae-9b8f-4c32-af84-9f3ee767ba1d.jpg"
    }
}
