// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.jou.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter


/**
 * Banishing Light
 * {2}{W}
 * Enchantment
 * When this enchantment enters, exile target nonland permanent an opponent controls until this enchantment leaves the battlefield.
 */
val BanishingLight = card("Banishing Light") {
    manaCost = "{2}{W}"
    colorIdentity = "W"
    typeLine = "Enchantment"
    oracleText = "When this enchantment enters, exile target nonland permanent an opponent controls until this enchantment leaves the battlefield."
    triggeredAbility {
        trigger = Triggers.self.enters()
        val t = target(TargetFilter.NonlandPermanentOpponentControls)
        effect = Effects.ExileUntilLeaves(t)
    }
    triggeredAbility {
        trigger = Triggers.self.leaves()
        effect = Effects.ReturnLinkedExileUnderOwnersControl()
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "5"
        artist = "Willian Murai"
        imageUri = "https://cards.scryfall.io/normal/front/f/b/fbaa4800-30cc-4a80-a6cc-9a24ada9eb40.jpg"
    }
}
