// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mid.cards

import com.wingedsheep.sdk.core.CounterType
import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.KeywordAbility
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter


/**
 * Angelfire Ignition
 * {1}{R}{W}
 * Sorcery
 * Put two +1/+1 counters on target creature. It gains vigilance, trample, lifelink, indestructible, and haste until end of turn.
 * Flashback {2}{R}{W} (You may cast this card from your graveyard for its flashback cost. Then exile it.)
 */
val AngelfireIgnition = card("Angelfire Ignition") {
    manaCost = "{1}{R}{W}"
    colorIdentity = "WR"
    typeLine = "Sorcery"
    oracleText = "Put two +1/+1 counters on target creature. It gains vigilance, trample, lifelink, indestructible, and haste until end of turn.\nFlashback {2}{R}{W} (You may cast this card from your graveyard for its flashback cost. Then exile it.)"
    spell {
        val t = target(TargetFilter.Creature)
        effect = Effects.AddCounters(counterType = CounterType.PLUS_ONE_PLUS_ONE, count = 2, target = t) then
            Effects.GrantKeyword(Keyword.VIGILANCE, t) then
            Effects.GrantKeyword(Keyword.TRAMPLE, t) then
            Effects.GrantKeyword(Keyword.LIFELINK, t) then
            Effects.GrantKeyword(Keyword.INDESTRUCTIBLE, t) then
            Effects.GrantKeyword(Keyword.HASTE, t)
    }
    keywordAbility(KeywordAbility.flashback("{2}{R}{W}"))
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "209"
        artist = "Yeong-Hao Han"
        flavorText = "\"My angel is the flint, and I am her steel.\""
        imageUri = "https://cards.scryfall.io/normal/front/8/b/8ba4c7a2-6243-43ed-8c1c-e3edee43a583.jpg"
    }
}
