// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.wth.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter


/**
 * Guided Strike
 * {1}{W}
 * Instant
 * Target creature gets +1/+0 and gains first strike until end of turn.
 * Draw a card.
 */
val GuidedStrike = card("Guided Strike") {
    manaCost = "{1}{W}"
    colorIdentity = "W"
    typeLine = "Instant"
    oracleText = "Target creature gets +1/+0 and gains first strike until end of turn.\nDraw a card."
    spell {
        val t = target(TargetFilter.Creature)
        effect = Effects.ModifyStats(1, 0, t) then
            Effects.GrantKeyword(Keyword.FIRST_STRIKE, t) then
            Effects.DrawCards(1)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "16"
        artist = "Gary Leach"
        flavorText = "\"If you can kill your enemy with the first stroke, you save yourself the labor of the second.\"\n—Gerrard of the Weatherlight"
        imageUri = "https://cards.scryfall.io/normal/front/c/6/c6e8ec37-abe8-45a9-a1a0-6d4e37c74c45.jpg"
    }
}
