// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.hob.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.dsl.mode
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.effects.ModalEffect
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter


/**
 * Elven Raft-Steerer
 * {2}{U}
 * Creature — Elf Pilot
 * 3/2
 * Landfall — Whenever a land you control enters, choose one —
 * • Tap target creature an opponent controls.
 * • Untap target creature you control.
 */
val ElvenRaftSteerer = card("Elven Raft-Steerer") {
    manaCost = "{2}{U}"
    colorIdentity = "U"
    typeLine = "Creature — Elf Pilot"
    oracleText = "Landfall — Whenever a land you control enters, choose one —\n• Tap target creature an opponent controls.\n• Untap target creature you control."
    power = 3
    toughness = 2
    triggeredAbility {
        trigger = Triggers.a(GameObjectFilter.Land.youControl()).enters()
        effect = ModalEffect.chooseOne(
            mode("Tap target creature an opponent controls") {
                val creature = target(TargetFilter.Creature.opponentControls())
                effect = Effects.Tap(creature)
            },
            mode("Untap target creature you control") {
                val creature = target(TargetFilter.Creature.youControl())
                effect = Effects.Untap(creature)
            }
        )
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "37"
        artist = "Christina Kraus"
        flavorText = "\"Float beyond the world of trees\nOut into the whispering breeze.\""
        imageUri = "https://cards.scryfall.io/normal/front/c/1/c141695c-c108-41d5-85cb-1f7485d9d533.jpg"
    }
}
