// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.usg.cards

import com.wingedsheep.sdk.core.CounterType
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter


/**
 * Dragon Blood
 * {3}
 * Artifact
 * {3}, {T}: Put a +1/+1 counter on target creature.
 */
val DragonBlood = card("Dragon Blood") {
    manaCost = "{3}"
    colorIdentity = ""
    typeLine = "Artifact"
    oracleText = "{3}, {T}: Put a +1/+1 counter on target creature."
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{3}"), Costs.Tap)
        val t = target(TargetFilter.Creature)
        effect = Effects.AddCounters(counterType = CounterType.PLUS_ONE_PLUS_ONE, count = 1, target = t)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "293"
        artist = "Greg Simanson"
        flavorText = "Fire in the blood, fire in the belly."
        imageUri = "https://cards.scryfall.io/normal/front/f/f/ff72806a-ae41-44f5-ad74-56c3338ebfcb.jpg"
    }
}
