// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.chk.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.Duration
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter


/**
 * Blind with Anger
 * {3}{R}
 * Instant — Arcane
 * Untap target nonlegendary creature and gain control of it until end of turn. That creature gains haste until end of turn.
 */
val BlindWithAnger = card("Blind with Anger") {
    manaCost = "{3}{R}"
    colorIdentity = "R"
    typeLine = "Instant — Arcane"
    oracleText = "Untap target nonlegendary creature and gain control of it until end of turn. That creature gains haste until end of turn."
    spell {
        val t = target(TargetFilter.Creature.nonlegendary())
        effect = Effects.Untap(t) then
            Effects.GainControl(t, Duration.EndOfTurn) then
            Effects.GrantKeyword(Keyword.HASTE, t)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "158"
        artist = "Dave Dorman"
        flavorText = "\"I can post only the most honorable and strong-willed samurai to defend your stronghold. I have seen what can happen to lesser men.\"\n—General Takeno, letter to Lord Konda"
        imageUri = "https://cards.scryfall.io/normal/front/a/5/a50a0fe0-249d-4a88-a538-cdf622388ce2.jpg"
    }
}
