// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.chk.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter


/**
 * Terashi's Cry
 * {3}{W}
 * Sorcery — Arcane
 * Tap up to three target creatures.
 */
val TerashisCry = card("Terashi's Cry") {
    manaCost = "{3}{W}"
    colorIdentity = "W"
    typeLine = "Sorcery — Arcane"
    oracleText = "Tap up to three target creatures."
    spell {
        targets(TargetFilter.Creature, count = 3, optional = true)
        effect = Effects.TapEachTarget()
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "47"
        artist = "Jim Murray"
        flavorText = "\"The sun kami is terrible to behold. When its temper flares, best seek shade and pray for forgiveness.\"\n—Sensei Golden-Tail"
        imageUri = "https://cards.scryfall.io/normal/front/7/1/7176139f-8a9a-4ee4-a56d-672fd09390e4.jpg"
    }
}
