// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mir.cards

import com.wingedsheep.sdk.dsl.DynamicAmounts
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.references.Player


/**
 * Divine Retribution
 * {1}{W}
 * Instant
 * Divine Retribution deals damage to target attacking creature equal to the number of attacking creatures.
 */
val DivineRetribution = card("Divine Retribution") {
    manaCost = "{1}{W}"
    colorIdentity = "W"
    typeLine = "Instant"
    oracleText = "Divine Retribution deals damage to target attacking creature equal to the number of attacking creatures."
    spell {
        val t = target(TargetFilter.Creature.attacking())
        effect = Effects.DealDamage(
            DynamicAmounts.battlefield(Player.Each, GameObjectFilter.Creature.attacking()).count(),
            t
        )
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "12"
        artist = "Charles Gillespie"
        flavorText = "\"To the undiscerning eye, justice and vengeance can look the same.\"\n—Rashida Scalebane"
        imageUri = "https://cards.scryfall.io/normal/front/7/5/75629aa3-426e-4e25-a7ab-71e03436e061.jpg"
    }
}
