// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mir.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter


/**
 * Femeref Archers
 * {2}{G}
 * Creature — Human Archer
 * 2/2
 * {T}: This creature deals 4 damage to target attacking creature with flying.
 */
val FemerefArchers = card("Femeref Archers") {
    manaCost = "{2}{G}"
    colorIdentity = "G"
    typeLine = "Creature — Human Archer"
    oracleText = "{T}: This creature deals 4 damage to target attacking creature with flying."
    power = 2
    toughness = 2
    activatedAbility {
        cost = Costs.Tap
        val t = target(TargetFilter.Creature.withKeyword(Keyword.FLYING).attacking())
        effect = Effects.DealDamage(4, t)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "215"
        artist = "William Donohoe"
        flavorText = "\"They say a Zhalfirin archer can split the eye of a griffin. Nonsense, of course: they have no faith to guide their darts.\"\n—Nuru, Femeref archer"
        imageUri = "https://cards.scryfall.io/normal/front/e/8/e859180f-084c-4023-848a-96f22b8f9698.jpg"
    }
}
