// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mir.cards

import com.wingedsheep.sdk.dsl.DynamicAmounts
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.dsl.divRoundedUp
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.references.Player
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Infernal Contract
 * {B}{B}{B}
 * Sorcery
 * Draw four cards. You lose half your life, rounded up.
 */
val InfernalContract = card("Infernal Contract") {
    manaCost = "{B}{B}{B}"
    colorIdentity = "B"
    typeLine = "Sorcery"
    oracleText = "Draw four cards. You lose half your life, rounded up."
    spell {
        effect = Effects.DrawCards(4) then
            Effects.LoseLife(
                DynamicAmounts.lifeTotal(Player.You) divRoundedUp 2,
                EffectTarget.Controller
            )
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "129"
        artist = "Roger Raupp"
        flavorText = "\"But I signed nothing!\"\n—Taraneh, Suq'Ata mage"
        imageUri = "https://cards.scryfall.io/normal/front/e/6/e62c43bd-59fe-46e3-83f8-c4b37cbc4931.jpg"
    }
}
