// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mir.cards

import com.wingedsheep.sdk.dsl.DynamicAmounts
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.dsl.Targets


/**
 * Volcanic Geyser
 * {X}{R}{R}
 * Instant
 * Volcanic Geyser deals X damage to any target.
 */
val VolcanicGeyser = card("Volcanic Geyser") {
    manaCost = "{X}{R}{R}"
    colorIdentity = "R"
    typeLine = "Instant"
    oracleText = "Volcanic Geyser deals X damage to any target."
    spell {
        val t = target(Targets.Any)
        effect = Effects.DealDamage(DynamicAmounts.xValue(), t)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "202"
        artist = "David O'Connor"
        flavorText = "My thunder comes before the lightning; my lightning comes before the clouds; my rain dries all the land it touches. What am I?\n—Femeref riddle"
        imageUri = "https://cards.scryfall.io/normal/front/9/1/911787db-9023-46f8-9501-3ad26b6ca51d.jpg"
    }
}
