// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.woe.cards

import com.wingedsheep.sdk.core.Subtype
import com.wingedsheep.sdk.dsl.Conditions
import com.wingedsheep.sdk.dsl.DynamicAmounts
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.dsl.unaryMinus
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter


/**
 * Faerie Fencing
 * {X}{B}
 * Instant
 * Target creature gets -X/-X until end of turn. That creature gets an additional -3/-3 until end of turn if you controlled a Faerie as you cast this spell.
 */
val FaerieFencing = card("Faerie Fencing") {
    manaCost = "{X}{B}"
    colorIdentity = "B"
    typeLine = "Instant"
    oracleText = "Target creature gets -X/-X until end of turn. That creature gets an additional -3/-3 until end of turn if you controlled a Faerie as you cast this spell."
    spell {
        captureAtCast("controlledFaerie", Conditions.YouControl(GameObjectFilter.Creature.withSubtype(Subtype.FAERIE)))
        val t = target(TargetFilter.Creature)
        effect = Effects.If(
            condition = Conditions.CapturedAtCast("controlledFaerie"),
            then = Effects.ModifyStats(
                -DynamicAmounts.xValue(),
                -DynamicAmounts.xValue(),
                t
            ) then
                Effects.ModifyStats(-3, -3, t),
            otherwise = Effects.ModifyStats(
                -DynamicAmounts.xValue(),
                -DynamicAmounts.xValue(),
                t
            )
        )
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "90"
        artist = "Evyn Fong"
        flavorText = "Even in the grip of the Wicked Slumber, the High Fae princess Obyra is a blademaster of unrivaled skill."
        imageUri = "https://cards.scryfall.io/normal/front/6/b/6bdcaf24-4352-47cf-a043-899be47ab1bb.jpg"
    }
}
