// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.woe.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter


/**
 * Plunge into Winter
 * {1}{W}
 * Instant
 * Tap up to one target creature. Scry 1, then draw a card.
 */
val PlungeIntoWinter = card("Plunge into Winter") {
    manaCost = "{1}{W}"
    colorIdentity = "W"
    typeLine = "Instant"
    oracleText = "Tap up to one target creature. Scry 1, then draw a card."
    spell {
        val t = target(TargetFilter.Creature, optional = true)
        effect = Effects.Tap(t) then
            Patterns.Library.scry(1) then
            Effects.DrawCards(1)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "22"
        artist = "Vincent Christiaens"
        flavorText = "When Hylda froze Loch Larent to create her palace, some merfolk dove deep enough underwater to escape the chill. Others weren't so lucky."
        imageUri = "https://cards.scryfall.io/normal/front/f/e/fe4aceba-f386-457c-bc68-6382eda46754.jpg"
    }
}
