// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.por.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter


/**
 * Alluring Scent
 * {1}{G}{G}
 * Sorcery
 * All creatures able to block target creature this turn do so.
 */
val AlluringScent = card("Alluring Scent") {
    manaCost = "{1}{G}{G}"
    colorIdentity = "G"
    typeLine = "Sorcery"
    oracleText = "All creatures able to block target creature this turn do so."
    spell {
        val t = target(TargetFilter.Creature)
        effect = Effects.MustBeBlocked(t)
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "157"
        artist = "Ted Naifeh"
        flavorText = "Doom rarely smells this sweet."
        imageUri = "https://cards.scryfall.io/normal/front/8/7/8726242e-bfd8-4ed5-a016-ac0c82e4762b.jpg"
    }
}
