// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.por.cards

import com.wingedsheep.sdk.dsl.DynamicAmounts
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.dsl.Targets


/**
 * Blaze
 * {X}{R}
 * Sorcery
 * Blaze deals X damage to any target.
 */
val Blaze = card("Blaze") {
    manaCost = "{X}{R}"
    colorIdentity = "R"
    typeLine = "Sorcery"
    oracleText = "Blaze deals X damage to any target."
    spell {
        val t = target(Targets.Any)
        effect = Effects.DealDamage(DynamicAmounts.xValue(), t)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "118"
        artist = "Gerry Grace"
        flavorText = "Fire never dies alone."
        imageUri = "https://cards.scryfall.io/normal/front/f/1/f175c959-3b5d-46a3-9194-fad2359bbff9.jpg"
    }
}
