// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.por.cards

import com.wingedsheep.sdk.dsl.DynamicAmounts
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.dsl.times
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.references.Player


/**
 * Blessed Reversal
 * {1}{W}
 * Instant
 * You gain 3 life for each creature attacking you.
 */
val BlessedReversal = card("Blessed Reversal") {
    manaCost = "{1}{W}"
    colorIdentity = "W"
    typeLine = "Instant"
    oracleText = "You gain 3 life for each creature attacking you."
    spell {
        effect = Effects.GainLife(
            DynamicAmounts.battlefield(Player.EachOpponent, GameObjectFilter.Creature.attacking()).count() * 3
        )
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "7"
        artist = "Zina Saunders"
        imageUri = "https://cards.scryfall.io/normal/front/8/9/899ecc19-8106-4e5a-bb25-aaea9684ba0e.jpg"
    }
}
