// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.por.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.effects.CardSource
import com.wingedsheep.sdk.scripting.references.Player
import com.wingedsheep.sdk.scripting.targets.TargetOpponent
import com.wingedsheep.sdk.dsl.Targets


/**
 * Cruel Fate
 * {4}{U}
 * Sorcery
 * Look at the top five cards of target opponent's library. Put one of those cards into that player's graveyard and the rest on top of their library in any order.
 */
val CruelFate = card("Cruel Fate") {
    manaCost = "{4}{U}"
    colorIdentity = "U"
    typeLine = "Sorcery"
    oracleText = "Look at the top five cards of target opponent's library. Put one of those cards into that player's graveyard and the rest on top of their library in any order."
    spell {
        val t = target(Targets.Opponent)
        effect = Effects.Pipeline {
            val looked = gather(CardSource.TopOfLibrary(5, Player.TargetOpponent))
            val (toGraveyardCards, toTop) = chooseExactlySplit(
                1,
                from = looked,
                selectedLabel = "Put in graveyard",
                remainderLabel = "Put on top"
            )
            toGraveyard(toGraveyardCards, Player.TargetOpponent)
            toLibraryTop(toTop, Player.TargetOpponent)
        }
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "50"
        artist = "Adrian Smith"
        imageUri = "https://cards.scryfall.io/normal/front/4/4/44bea0d4-946e-4cb8-b6f1-50231d52bfbe.jpg"
    }
}
