// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.por.cards

import com.wingedsheep.sdk.dsl.DynamicAmounts
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.dsl.divRoundedUp
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.references.Player
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Cruel Bargain
 * {B}{B}{B}
 * Sorcery
 * Draw four cards. You lose half your life, rounded up.
 */
val CruelBargain = card("Cruel Bargain") {
    manaCost = "{B}{B}{B}"
    colorIdentity = "B"
    typeLine = "Sorcery"
    oracleText = "Draw four cards. You lose half your life, rounded up."
    spell {
        effect = Effects.DrawCards(4) then
            Effects.LoseLife(
                DynamicAmounts.lifeTotal(Player.You) divRoundedUp 2,
                EffectTarget.Controller
            )
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "86"
        artist = "Adrian Smith"
        imageUri = "https://cards.scryfall.io/normal/front/9/6/96837a9e-dd68-4ce8-b760-0e1c22837164.jpg"
    }
}
