// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.por.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter


/**
 * Fire Imp
 * {2}{R}
 * Creature — Imp
 * 2/1
 * When this creature enters, it deals 2 damage to target creature.
 */
val FireImp = card("Fire Imp") {
    manaCost = "{2}{R}"
    colorIdentity = "R"
    typeLine = "Creature — Imp"
    oracleText = "When this creature enters, it deals 2 damage to target creature."
    power = 2
    toughness = 1
    triggeredAbility {
        trigger = Triggers.self.enters()
        val t = target(TargetFilter.Creature)
        effect = Effects.DealDamage(2, t)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "126"
        artist = "DiTerlizzi"
        imageUri = "https://cards.scryfall.io/normal/front/e/a/ea7edaf3-7941-4085-bdbc-e5c9832b6444.jpg"
    }
}
