// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.por.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.TargetObject


/**
 * Forked Lightning
 * {3}{R}
 * Sorcery
 * Forked Lightning deals 4 damage divided as you choose among one, two, or three target creatures.
 */
val ForkedLightning = card("Forked Lightning") {
    manaCost = "{3}{R}"
    colorIdentity = "R"
    typeLine = "Sorcery"
    oracleText = "Forked Lightning deals 4 damage divided as you choose among one, two, or three target creatures."
    spell {
        target = TargetObject(filter = TargetFilter.Creature, count = 3, minCount = 1)
        effect = Effects.DividedDamage(total = 4, minTargets = 1, maxTargets = 3)
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "130"
        artist = "Ted Naifeh"
        imageUri = "https://cards.scryfall.io/normal/front/8/5/85883197-fd55-4e82-862f-87be4f789493.jpg"
    }
}
