// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.por.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Patterns
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity


/**
 * Omen
 * {1}{U}
 * Sorcery
 * Look at the top three cards of your library, then put them back in any order. You may shuffle.
 * Draw a card.
 */
val Omen = card("Omen") {
    manaCost = "{1}{U}"
    colorIdentity = "U"
    typeLine = "Sorcery"
    oracleText = "Look at the top three cards of your library, then put them back in any order. You may shuffle.\nDraw a card."
    spell {
        effect = Patterns.Library.lookAtTopAndReorder(count = 3) then
            Effects.May(Effects.ShuffleLibrary()) then
            Effects.DrawCards(1)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "62"
        artist = "Eric Peterson"
        imageUri = "https://cards.scryfall.io/normal/front/6/b/6be1956e-c43e-4a6c-950a-5be6e6ca013f.jpg"
    }
}
