// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.por.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter


/**
 * Tidal Surge
 * {1}{U}
 * Sorcery
 * Tap up to three target creatures without flying.
 */
val TidalSurge = card("Tidal Surge") {
    manaCost = "{1}{U}"
    colorIdentity = "U"
    typeLine = "Sorcery"
    oracleText = "Tap up to three target creatures without flying."
    spell {
        targets(TargetFilter.Creature.withoutKeyword(Keyword.FLYING), count = 3, optional = true)
        effect = Effects.TapEachTarget()
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "74"
        artist = "Douglas Shuler"
        flavorText = "\"'Twas when the seas were roaring With hollow blasts of wind . . . .\"\n—John Gay, \"The What D'Ye Call It\""
        imageUri = "https://cards.scryfall.io/normal/front/a/0/a027c31d-c662-4ce1-a0d1-a32e62f6a724.jpg"
    }
}
