// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.vow.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.EffectTarget
import com.wingedsheep.sdk.core.Step


/**
 * Markov Waltzer
 * {2}{R}{W}
 * Creature — Vampire
 * 1/3
 * Flying, haste
 * At the beginning of combat on your turn, up to two target creatures you control each get +1/+0 until end of turn.
 */
val MarkovWaltzer = card("Markov Waltzer") {
    manaCost = "{2}{R}{W}"
    colorIdentity = "WR"
    typeLine = "Creature — Vampire"
    oracleText = "Flying, haste\nAt the beginning of combat on your turn, up to two target creatures you control each get +1/+0 until end of turn."
    power = 1
    toughness = 3
    keywords(Keyword.FLYING, Keyword.HASTE)
    triggeredAbility {
        trigger = Triggers.you.beginningOf(Step.BEGIN_COMBAT)
        targets(TargetFilter.Creature.youControl(), count = 2, optional = true)
        effect = Effects.ForEachTarget(Effects.ModifyStats(1, 0, EffectTarget.ContextTarget(0)))
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "242"
        artist = "Joshua Raphael"
        flavorText = "\"I'll lead.\""
        imageUri = "https://cards.scryfall.io/normal/front/c/2/c2f45bc0-36ed-44ec-9bc8-31ea7c7fafdb.jpg"
    }
}
