// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.vow.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.DynamicAmounts
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.TimingRule
import com.wingedsheep.sdk.scripting.effects.CardSource
import com.wingedsheep.sdk.core.Step


/**
 * Vilespawn Spider
 * {G}{U}
 * Creature — Spider
 * 2/3
 * Reach
 * At the beginning of your upkeep, mill a card. (Put the top card of your library into your graveyard.)
 * {2}{G}{U}, {T}, Sacrifice this creature: Create a 1/1 green Insect creature token for each creature card in your graveyard. Activate only as a sorcery.
 */
val VilespawnSpider = card("Vilespawn Spider") {
    manaCost = "{G}{U}"
    colorIdentity = "UG"
    typeLine = "Creature — Spider"
    oracleText = "Reach\nAt the beginning of your upkeep, mill a card. (Put the top card of your library into your graveyard.)\n{2}{G}{U}, {T}, Sacrifice this creature: Create a 1/1 green Insect creature token for each creature card in your graveyard. Activate only as a sorcery."
    power = 2
    toughness = 3
    keywords(Keyword.REACH)
    triggeredAbility {
        trigger = Triggers.you.beginningOf(Step.UPKEEP)
        effect = Effects.Pipeline {
            val milledThisWay = gather(CardSource.TopOfLibrary(1))
            toGraveyard(milledThisWay)
        }
    }
    activatedAbility {
        cost = Costs.Composite(Costs.Mana("{2}{G}{U}"), Costs.Tap, Costs.SacrificeSelf)
        effect = Effects.CreateToken(
            count = DynamicAmounts.creatureCardsInYourGraveyard(),
            power = 1,
            toughness = 1,
            colors = setOf(Color.GREEN),
            creatureTypes = setOf("Insect")
        )
        timing = TimingRule.SorcerySpeed
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "250"
        artist = "Nicholas Gregory"
        imageUri = "https://cards.scryfall.io/normal/front/6/a/6ad9ae64-6526-4747-9b0c-77d113f58c33.jpg"
    }
}
