// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.isd.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.DynamicAmounts
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.references.Player


/**
 * Elder of Laurels
 * {2}{G}
 * Creature — Human Advisor
 * 2/3
 * {3}{G}: Target creature gets +X/+X until end of turn, where X is the number of creatures you control.
 */
val ElderOfLaurels = card("Elder of Laurels") {
    manaCost = "{2}{G}"
    colorIdentity = "G"
    typeLine = "Creature — Human Advisor"
    oracleText = "{3}{G}: Target creature gets +X/+X until end of turn, where X is the number of creatures you control."
    power = 2
    toughness = 3
    activatedAbility {
        cost = Costs.Mana("{3}{G}")
        val t = target(TargetFilter.Creature)
        effect = Effects.ModifyStats(
            DynamicAmounts.creaturesYouControl(),
            DynamicAmounts.creaturesYouControl(),
            t
        )
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "177"
        artist = "Terese Nielsen"
        flavorText = "Hopes and prayers can carry the same force as swords and torches."
        imageUri = "https://cards.scryfall.io/normal/front/3/2/32b82ef0-c974-4357-b21a-4c2a28ec7279.jpg"
    }
}
