// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.isd.cards

import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter


/**
 * Lost in the Mist
 * {3}{U}{U}
 * Instant
 * Counter target spell. Return target permanent to its owner's hand.
 */
val LostInTheMist = card("Lost in the Mist") {
    manaCost = "{3}{U}{U}"
    colorIdentity = "U"
    typeLine = "Instant"
    oracleText = "Counter target spell. Return target permanent to its owner's hand."
    spell {
        val t1 = target(TargetFilter.SpellOnStack)
        val t2 = target(TargetFilter.Permanent)
        effect = Effects.CounterSpell() then Effects.Move(t2, Zone.HAND)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "63"
        artist = "David Palumbo"
        flavorText = "The secrets she carried could have saved many lives, but they quietly drowned with her."
        imageUri = "https://cards.scryfall.io/normal/front/1/e/1e5fc39d-590a-436b-ab90-a1741d2ae3da.jpg"
    }
}
