// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.tmp.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.dsl.Targets


/**
 * Lightning Blast
 * {3}{R}
 * Instant
 * Lightning Blast deals 4 damage to any target.
 */
val LightningBlast = card("Lightning Blast") {
    manaCost = "{3}{R}"
    colorIdentity = "R"
    typeLine = "Instant"
    oracleText = "Lightning Blast deals 4 damage to any target."
    spell {
        val t = target(Targets.Any)
        effect = Effects.DealDamage(4, t)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "185"
        artist = "Richard Thomas"
        flavorText = "\"Those who fear the darkness have never seen what the light can do.\"\n—Selenia, dark angel"
        imageUri = "https://cards.scryfall.io/normal/front/6/3/63fec3f9-d399-48e6-84b6-c8410c24c382.jpg"
    }
}
