// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mkm.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.DynamicAmounts
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.references.Player


/**
 * Get a Leg Up
 * {G}
 * Instant
 * Until end of turn, target creature gets +1/+1 for each creature you control and gains reach.
 */
val GetALegUp = card("Get a Leg Up") {
    manaCost = "{G}"
    colorIdentity = "G"
    typeLine = "Instant"
    oracleText = "Until end of turn, target creature gets +1/+1 for each creature you control and gains reach."
    spell {
        val t = target(TargetFilter.Creature)
        effect = Effects.ModifyStats(
            DynamicAmounts.creaturesYouControl(),
            DynamicAmounts.creaturesYouControl(),
            t
        ) then
            Effects.GrantKeyword(Keyword.REACH, t)
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "161"
        artist = "Jesper Ejsing"
        flavorText = "\"Apologies for using you like a stepladder. On the other hand, thank you, you're a wonderful stepladder!\""
        imageUri = "https://cards.scryfall.io/normal/front/3/4/34e61e0f-d0f3-492a-92f1-36f72a91583a.jpg"
    }
}
