// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.apc.cards

import com.wingedsheep.sdk.dsl.DynamicAmounts
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.dsl.Targets


/**
 * Death Grasp
 * {X}{W}{B}
 * Sorcery
 * Death Grasp deals X damage to any target. You gain X life.
 */
val DeathGrasp = card("Death Grasp") {
    manaCost = "{X}{W}{B}"
    colorIdentity = "WB"
    typeLine = "Sorcery"
    oracleText = "Death Grasp deals X damage to any target. You gain X life."
    spell {
        val t = target(Targets.Any)
        effect = Effects.DealDamage(DynamicAmounts.xValue(), t) then Effects.GainLife(DynamicAmounts.xValue())
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "95"
        artist = "Eric Peterson"
        flavorText = "Yawgmoth's greatest joy came from watching one hero defeat another."
        imageUri = "https://cards.scryfall.io/normal/front/0/e/0e893dd4-8c37-496e-bc39-cd83d42b4cc4.jpg"
    }
}
