// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.apc.cards

import com.wingedsheep.sdk.dsl.Costs
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter


/**
 * Overgrown Estate
 * {W}{B}{G}
 * Enchantment
 * Sacrifice a land: You gain 3 life.
 */
val OvergrownEstate = card("Overgrown Estate") {
    manaCost = "{W}{B}{G}"
    colorIdentity = "WBG"
    typeLine = "Enchantment"
    oracleText = "Sacrifice a land: You gain 3 life."
    activatedAbility {
        cost = Costs.Sacrifice(GameObjectFilter.Land)
        effect = Effects.GainLife(3)
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "113"
        artist = "Brian Snõddy"
        flavorText = "The decay of Crovax's ancestral home matched the state of his soul."
        imageUri = "https://cards.scryfall.io/normal/front/c/1/c1c48c58-3532-4022-9eec-1a870385cbf3.jpg"
    }
}
