// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.nem.cards

import com.wingedsheep.sdk.core.AbilityFlag
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter


/**
 * Infiltrate
 * {U}
 * Instant
 * Target creature can't be blocked this turn.
 */
val Infiltrate = card("Infiltrate") {
    manaCost = "{U}"
    colorIdentity = "U"
    typeLine = "Instant"
    oracleText = "Target creature can't be blocked this turn."
    spell {
        val t = target(TargetFilter.Creature)
        effect = Effects.GrantKeyword(AbilityFlag.CANT_BE_BLOCKED, t)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "33"
        artist = "Nelson DeCastro"
        flavorText = "Getting in was the easy part. Getting out proved to be more difficult."
        imageUri = "https://cards.scryfall.io/normal/front/c/5/c549b817-8ad6-44d0-9761-5e4ff9e62c71.jpg"
    }
}
