// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.nem.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter


/**
 * Vicious Hunger
 * {B}{B}
 * Sorcery
 * Vicious Hunger deals 2 damage to target creature and you gain 2 life.
 */
val ViciousHunger = card("Vicious Hunger") {
    manaCost = "{B}{B}"
    colorIdentity = "B"
    typeLine = "Sorcery"
    oracleText = "Vicious Hunger deals 2 damage to target creature and you gain 2 life."
    spell {
        val t = target(TargetFilter.Creature)
        effect = Effects.DealDamage(2, t) then Effects.GainLife(2)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "74"
        artist = "Massimiliano Frezzato"
        flavorText = "\"Blood is foul, the flesh dross. My ascendance thirsts for life itself.\"\n—Crovax"
        imageUri = "https://cards.scryfall.io/normal/front/c/c/ccaff6a0-7831-45db-a50f-881c6cb7ce49.jpg"
    }
}
