// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mmq.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.dsl.Targets


/**
 * Highway Robber
 * {2}{B}{B}
 * Creature — Human Mercenary
 * 2/2
 * When this creature enters, target opponent loses 2 life and you gain 2 life.
 */
val HighwayRobber = card("Highway Robber") {
    manaCost = "{2}{B}{B}"
    colorIdentity = "B"
    typeLine = "Creature — Human Mercenary"
    oracleText = "When this creature enters, target opponent loses 2 life and you gain 2 life."
    power = 2
    toughness = 2
    triggeredAbility {
        trigger = Triggers.self.enters()
        val t = target(Targets.Opponent)
        effect = Effects.LoseLife(2, t) then Effects.GainLife(2)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "139"
        artist = "Kev Walker"
        flavorText = "\"Tonight, madam, it's your money and your life.\""
        imageUri = "https://cards.scryfall.io/normal/front/f/c/fc826c88-fe3c-4004-8283-27910c550fae.jpg"
    }
}
