// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.vis.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.dsl.Targets


/**
 * Inspiration
 * {3}{U}
 * Instant
 * Target player draws two cards.
 */
val Inspiration = card("Inspiration") {
    manaCost = "{3}{U}"
    colorIdentity = "U"
    typeLine = "Instant"
    oracleText = "Target player draws two cards."
    spell {
        val t = target(Targets.Player)
        effect = Effects.DrawCards(2, t)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "35"
        artist = "Zina Saunders"
        flavorText = "\"Madness and genius are separated only by degrees of success.\"\n—Sidar Jabari"
        imageUri = "https://cards.scryfall.io/normal/front/5/2/5247d0b0-660e-4f27-8e76-62effbe12221.jpg"
    }
}
