// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.fin.cards

import com.wingedsheep.sdk.core.Color
import com.wingedsheep.sdk.dsl.DynamicAmounts
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.TriggeredAbility
import com.wingedsheep.sdk.scripting.targets.EffectTarget
import com.wingedsheep.sdk.dsl.Targets


/**
 * Choco-Comet
 * {X}{R}{R}
 * Sorcery
 * Choco-Comet deals X damage to any target.
 * Create a 2/2 green Bird creature token with "Whenever a land you control enters, this token gets +1/+0 until end of turn."
 */
val ChocoComet = card("Choco-Comet") {
    manaCost = "{X}{R}{R}"
    colorIdentity = "R"
    typeLine = "Sorcery"
    oracleText = "Choco-Comet deals X damage to any target.\nCreate a 2/2 green Bird creature token with \"Whenever a land you control enters, this token gets +1/+0 until end of turn.\""
    spell {
        val t = target(Targets.Any)
        effect = Effects.DealDamage(DynamicAmounts.xValue(), t) then
            Effects.CreateToken(
                power = 2,
                toughness = 2,
                colors = setOf(Color.GREEN),
                creatureTypes = setOf("Bird"),
                imageUri = "https://cards.scryfall.io/normal/front/1/f/1fbc471d-5948-47fc-b7cc-81cc13a4cd15.jpg?1748704082",
                triggeredAbilities = listOf(
                    TriggeredAbility.create(
                        trigger = Triggers.a(GameObjectFilter.Land.youControl()).enters(),
                        effect = Effects.ModifyStats(1, 0, EffectTarget.Self)
                    )
                )
            )
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "132"
        artist = "Fiona Hsieh"
        flavorText = "The other colorations of chocobo tend to be quite violent, giving rise to the saying: \"Yellow, best for riding; aught else, best be hiding.\""
        imageUri = "https://cards.scryfall.io/normal/front/8/d/8d8d3903-a7f4-4cd8-8d29-b4a173e4fbb2.jpg"
    }
}
