// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.fin.cards

import com.wingedsheep.sdk.core.CounterType
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.dsl.Targets


/**
 * Combat Tutorial
 * {2}{U}
 * Sorcery
 * Target player draws two cards. Put a +1/+1 counter on up to one target creature you control.
 */
val CombatTutorial = card("Combat Tutorial") {
    manaCost = "{2}{U}"
    colorIdentity = "U"
    typeLine = "Sorcery"
    oracleText = "Target player draws two cards. Put a +1/+1 counter on up to one target creature you control."
    spell {
        val t1 = target(Targets.Player)
        val t2 = target(TargetFilter.Creature.youControl(), optional = true)
        effect = Effects.DrawCards(2, t1) then
            Effects.AddCounters(counterType = CounterType.PLUS_ONE_PLUS_ONE, count = 1, target = t2)
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "48"
        artist = "Fang Xinyu"
        flavorText = "\"Clueless, aren't you? Good thing I'm here.\"\n—Lulu"
        imageUri = "https://cards.scryfall.io/normal/front/e/c/ec195607-ac30-4931-acfd-f9d8ac8b047f.jpg"
    }
}
