// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.mrd.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.references.Player
import com.wingedsheep.sdk.scripting.targets.EffectTarget
import com.wingedsheep.sdk.core.Step


/**
 * Molder Slug
 * {3}{G}{G}
 * Creature — Slug Beast
 * 4/6
 * At the beginning of each player's upkeep, that player sacrifices an artifact of their choice.
 */
val MolderSlug = card("Molder Slug") {
    manaCost = "{3}{G}{G}"
    colorIdentity = "G"
    typeLine = "Creature — Slug Beast"
    oracleText = "At the beginning of each player's upkeep, that player sacrifices an artifact of their choice."
    power = 4
    toughness = 6
    triggeredAbility {
        trigger = Triggers.anyPlayer.beginningOf(Step.UPKEEP)
        effect = Effects.Sacrifice(GameObjectFilter.Artifact, 1, EffectTarget.PlayerRef(Player.TriggeringPlayer))
    }
    metadata {
        rarity = Rarity.RARE
        collectorNumber = "125"
        artist = "Heather Hudson"
        flavorText = "Fortunately for it, Mirrodin is a plane without salt."
        imageUri = "https://cards.scryfall.io/normal/front/e/e/ee355d1b-5d64-4328-94d6-7a58889b99bc.jpg"
    }
}
