// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.ptk.cards

import com.wingedsheep.sdk.dsl.DynamicAmounts
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.dsl.times
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.references.Player


/**
 * Peach Garden Oath
 * {W}
 * Sorcery
 * You gain 2 life for each creature you control.
 */
val PeachGardenOath = card("Peach Garden Oath") {
    manaCost = "{W}"
    colorIdentity = "W"
    typeLine = "Sorcery"
    oracleText = "You gain 2 life for each creature you control."
    spell {
        effect = Effects.GainLife(
            DynamicAmounts.creaturesYouControl() * 2
        )
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "15"
        artist = "Qiao Dafu"
        flavorText = "\"We three, though of separate ancestry, join in brotherhood . . . . We dare not hope to be together always but hereby vow to die the selfsame day.\"\n—Peach Garden Oath"
        imageUri = "https://cards.scryfall.io/normal/front/4/1/41bfd51a-0aca-4686-a9c5-11288f409a22.jpg"
    }
}
