// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.pcy.cards

import com.wingedsheep.sdk.core.Zone
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.references.Player
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Devastate
 * {3}{R}{R}
 * Sorcery
 * Destroy target land. Devastate deals 1 damage to each creature and each player.
 */
val Devastate = card("Devastate") {
    manaCost = "{3}{R}{R}"
    colorIdentity = "R"
    typeLine = "Sorcery"
    oracleText = "Destroy target land. Devastate deals 1 damage to each creature and each player."
    spell {
        val t = target(TargetFilter.Land)
        effect = Effects.Move(t, Zone.GRAVEYARD, byDestruction = true) then
            Effects.ForEachInGroup(GroupFilter(GameObjectFilter.Creature), Effects.DealDamage(1, EffectTarget.IterationEntity)) then
            Effects.ForEachPlayer(Player.Each, Effects.DealDamage(1, EffectTarget.Controller))
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "87"
        artist = "Greg Staples"
        flavorText = "\"You're willing to die for your homeland. I'm willing to kill for it.\"\n—Latulla, Keldon overseer"
        imageUri = "https://cards.scryfall.io/normal/front/b/f/bfe7c990-a34b-475e-a612-447c22f998d3.jpg"
    }
}
