// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dka.cards

import com.wingedsheep.sdk.dsl.Conditions
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter


/**
 * Tragic Slip
 * {B}
 * Instant
 * Target creature gets -1/-1 until end of turn.
 * Morbid — That creature gets -13/-13 until end of turn instead if a creature died this turn.
 */
val TragicSlip = card("Tragic Slip") {
    manaCost = "{B}"
    colorIdentity = "B"
    typeLine = "Instant"
    oracleText = "Target creature gets -1/-1 until end of turn.\nMorbid — That creature gets -13/-13 until end of turn instead if a creature died this turn."
    spell {
        val t = target(TargetFilter.Creature)
        effect = Effects.If(
            condition = Conditions.CreatureDiedThisTurn,
            then = Effects.ModifyStats(-13, -13, t),
            otherwise = Effects.ModifyStats(-1, -1, t)
        )
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "76"
        artist = "Christopher Moeller"
        flavorText = "Linger on death's door and risk being invited in."
        imageUri = "https://cards.scryfall.io/normal/front/0/9/09666671-601e-4fca-bdfb-fb288bf2672c.jpg"
    }
}
