// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.dmu.cards

import com.wingedsheep.sdk.core.Keyword
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.Triggers
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter


/**
 * Prayer of Binding
 * {3}{W}
 * Enchantment
 * Flash
 * When this enchantment enters, exile up to one target nonland permanent an opponent controls until this enchantment leaves the battlefield. You gain 2 life.
 */
val PrayerOfBinding = card("Prayer of Binding") {
    manaCost = "{3}{W}"
    colorIdentity = "W"
    typeLine = "Enchantment"
    oracleText = "Flash\nWhen this enchantment enters, exile up to one target nonland permanent an opponent controls until this enchantment leaves the battlefield. You gain 2 life."
    keywords(Keyword.FLASH)
    triggeredAbility {
        trigger = Triggers.self.enters()
        val t = target(TargetFilter.NonlandPermanentOpponentControls, optional = true)
        effect = Effects.ExileUntilLeaves(t) then Effects.GainLife(2)
    }
    triggeredAbility {
        trigger = Triggers.self.leaves()
        effect = Effects.ReturnLinkedExileUnderOwnersControl()
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "28"
        artist = "Wylie Beckert"
        flavorText = "When a Phyrexian agent cannot be killed, they must be contained."
        imageUri = "https://cards.scryfall.io/normal/front/3/2/322f90b6-6b49-458d-9d5b-b601bfdd0af8.jpg"
    }
}
