// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.jud.cards

import com.wingedsheep.sdk.dsl.DynamicAmounts
import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.references.Player


/**
 * Keep Watch
 * {2}{U}
 * Instant
 * Draw a card for each attacking creature.
 */
val KeepWatch = card("Keep Watch") {
    manaCost = "{2}{U}"
    colorIdentity = "U"
    typeLine = "Instant"
    oracleText = "Draw a card for each attacking creature."
    spell {
        effect = Effects.DrawCards(DynamicAmounts.battlefield(Player.Each, GameObjectFilter.Creature.attacking()).count())
    }
    metadata {
        rarity = Rarity.COMMON
        collectorNumber = "43"
        artist = "Fred Rahmqvist"
        flavorText = "\"I see their moral dilemmas. I see their raw courage. I see their self-sacrifice. I see our victory.\""
        imageUri = "https://cards.scryfall.io/normal/front/6/e/6e702ee4-62b5-4d3b-a202-8cac4b84591c.jpg"
    }
}
