// === GENERATED by mtgish-tooling from the mtgish oracle IR (predictive, approximate). ===
// Complete render — no manual wiring needed. Still review the rules text and add a passing
// scenario test before relying on it.

package com.wingedsheep.mtg.sets.definitions.jud.cards

import com.wingedsheep.sdk.dsl.Effects
import com.wingedsheep.sdk.dsl.card
import com.wingedsheep.sdk.model.Rarity
import com.wingedsheep.sdk.scripting.GameObjectFilter
import com.wingedsheep.sdk.scripting.filters.unified.GroupFilter
import com.wingedsheep.sdk.scripting.filters.unified.TargetFilter
import com.wingedsheep.sdk.scripting.targets.EffectTarget


/**
 * Swelter
 * {3}{R}
 * Sorcery
 * Swelter deals 2 damage to each of two target creatures.
 */
val Swelter = card("Swelter") {
    manaCost = "{3}{R}"
    colorIdentity = "R"
    typeLine = "Sorcery"
    oracleText = "Swelter deals 2 damage to each of two target creatures."
    spell {
        targets(TargetFilter.Creature, count = 2)
        effect = Effects.ForEachInGroup(GroupFilter(GameObjectFilter.Permanent), Effects.DealDamage(2, EffectTarget.IterationEntity))
    }
    metadata {
        rarity = Rarity.UNCOMMON
        collectorNumber = "101"
        artist = "Ben Thompson"
        flavorText = "No circle has a beginning, but many have foreseeable ends."
        imageUri = "https://cards.scryfall.io/normal/front/8/f/8f667c26-40f5-4ac5-87a4-cb03f70590a2.jpg"
    }
}
